name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - birdsonggame/start-fresh
  pull_request:
    branches:
      - birdsonggame/start-fresh

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make download script executable
        run: chmod +x bird_song_game/download_audio.sh || true

      - name: Run audio download script
        run: ./bird_song_game/download_audio.sh

      - name: List audio files
        run: ls -la bird_song_game/audio || echo "No audio folder"

      - name: 'Deploy to Azure Static Web Apps'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"          # root contains index.html
          api_location: ""           # not using Functions
          output_location: ""        # deploy root
